package vista.principal;

import java.awt.event.KeyAdapter;
import java.awt.event.KeyEvent;
import javax.swing.JTextField;

/**
 *
 * @author Luis Lavado
 */
public class FormRegistroGastos extends javax.swing.JInternalFrame {

    public FormRegistroGastos() {
        initComponents();
        validarTxt();
    }

    public void validarTxt() {
        SoloNumeros(Txtcantidad);
        SoloLetras(TxtMotivo);
    }

    public void SoloNumeros(JTextField a) {
        a.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isLetter(c)) {
                    e.consume();
                }
            }
        });
    }

    public void SoloLetras(JTextField a) {
        a.addKeyListener(new KeyAdapter() {
            public void keyTyped(KeyEvent e) {
                char c = e.getKeyChar();
                if (Character.isDigit(c)) {
                    //getToolkit().beep();
                    e.consume();
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        Txtcantidad = new javax.swing.JTextField();
        TxtMotivo = new javax.swing.JTextField();
        clockDigital1 = new org.edisoncor.gui.varios.ClockDigital();
        BtnCancelar = new org.edisoncor.gui.button.ButtonRect();
        BntRegisGasto = new org.edisoncor.gui.button.ButtonRect();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric4 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric6 = new org.edisoncor.gui.label.LabelMetric();
        Fecha = new com.toedter.calendar.JDateChooser();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setTitle("   REGISTROS DE GASTOS");
        setFont(new java.awt.Font("Monospaced", 3, 14)); // NOI18N
        setFrameIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/group.png"))); // NOI18N
        addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                formMouseClicked(evt);
            }
        });
        getContentPane().setLayout(new java.awt.GridBagLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255)));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Txtcantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtcantidadActionPerformed(evt);
            }
        });
        Txtcantidad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtcantidadKeyPressed(evt);
            }
        });
        jPanel1.add(Txtcantidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 40, 80, -1));

        TxtMotivo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtMotivoKeyPressed(evt);
            }
        });
        jPanel1.add(TxtMotivo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 220, -1));

        clockDigital1.setForeground(new java.awt.Color(51, 0, 255));
        clockDigital1.setFont(new java.awt.Font("Microsoft Sans Serif", 1, 12)); // NOI18N
        jPanel1.add(clockDigital1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, 94, 33));

        BtnCancelar.setBackground(new java.awt.Color(0, 255, 204));
        BtnCancelar.setText("Cancelar");
        jPanel1.add(BtnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 180, 100, -1));

        BntRegisGasto.setBackground(new java.awt.Color(102, 255, 204));
        BntRegisGasto.setText("Registrar");
        jPanel1.add(BntRegisGasto, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, 99, -1));

        labelMetric1.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelMetric1.setText("Fecha:");
        labelMetric1.setColorDeSombra(new java.awt.Color(255, 255, 102));
        labelMetric1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(labelMetric1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        labelMetric4.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric4.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelMetric4.setText("Motivo:");
        labelMetric4.setColorDeSombra(new java.awt.Color(255, 255, 102));
        labelMetric4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(labelMetric4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        labelMetric6.setForeground(new java.awt.Color(0, 0, 0));
        labelMetric6.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        labelMetric6.setText("Cantidad:");
        labelMetric6.setColorDeSombra(new java.awt.Color(255, 255, 102));
        labelMetric6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jPanel1.add(labelMetric6, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 40, -1, -1));
        jPanel1.add(Fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 120, -1, -1));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 12;
        gridBagConstraints.ipady = 45;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        getContentPane().add(jPanel1, gridBagConstraints);

        jMenuBar1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 255)));

        jMenu1.setText("Opciones");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Salir");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtcantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtcantidadActionPerformed

    }//GEN-LAST:event_TxtcantidadActionPerformed

    private void TxtcantidadKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtcantidadKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.TxtMotivo.requestFocus();
        }
    }//GEN-LAST:event_TxtcantidadKeyPressed

    private void TxtMotivoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtMotivoKeyPressed
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
        this.Fecha.requestFocus();
        }
    }//GEN-LAST:event_TxtMotivoKeyPressed

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        FormRegistroGastos fr= new FormRegistroGastos();
        
    }//GEN-LAST:event_formMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonRect BntRegisGasto;
    private org.edisoncor.gui.button.ButtonRect BtnCancelar;
    private com.toedter.calendar.JDateChooser Fecha;
    private javax.swing.JTextField TxtMotivo;
    private javax.swing.JTextField Txtcantidad;
    private org.edisoncor.gui.varios.ClockDigital clockDigital1;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric4;
    private org.edisoncor.gui.label.LabelMetric labelMetric6;
    // End of variables declaration//GEN-END:variables
}
