/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frontend1;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author lis_cs
 */
public class from_usuario extends javax.swing.JFrame {

    /*public void centraVentana() {
//Obtiene el tamaño de la pantalla
Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
// Obtiene el tamaño de la ventana de la aplicación
Dimension frameSize = getSize();
// Se asegura que el tamaño de la ventana de la aplicación
// no exceda el tamaño de la pantalla
if (frameSize.height > screenSize.height) {
frameSize.height = screenSize.height;
}
if (frameSize.width > screenSize.width) {
frameSize.width = screenSize.width;
}
// Centra la ventana de la aplicación sobre la pantalla
setLocation((screenSize.width - frameSize.width) / 2,
(screenSize.height - frameSize.height) / 2);
}*/
    public from_usuario() {
        initComponents();
    }
    public void Ingresar_Usuario() {

        char clave[] = Txtcontraseña.getPassword();
        String clavedef = new String(clave);

        if (Txtusuario.getText().equals("Luis") && clavedef.equals("dba123456")) {

            this.dispose();

            JOptionPane.showMessageDialog(null, "Bienvenido\n"
                    + "Has ingresado satisfactoriamente al sistema", "Mensaje de bienvenida",
                    JOptionPane.INFORMATION_MESSAGE);

        } else {

            JOptionPane.showMessageDialog(null, "Acceso denegado:\n"
                    + "Por favor ingrese un usuario y/o contraseña correctos", "Acceso denegado",
                    JOptionPane.ERROR_MESSAGE);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new org.edisoncor.gui.panel.Panel();
        labelMetric1 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric2 = new org.edisoncor.gui.label.LabelMetric();
        labelMetric3 = new org.edisoncor.gui.label.LabelMetric();
        Txtusuario = new org.edisoncor.gui.textField.TextField();
        Txtcontraseña = new org.edisoncor.gui.passwordField.PasswordField();
        clockDigital1 = new org.edisoncor.gui.varios.ClockDigital();
        BotIniciaSecion = new org.edisoncor.gui.button.ButtonTextDown();
        jProgressBar1 = new javax.swing.JProgressBar();
        labelMetric4 = new org.edisoncor.gui.label.LabelMetric();
        Txtusuario1 = new org.edisoncor.gui.textField.TextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("BIENBENIDO A CONSORSIO PARISAN PERU");
        setMaximizedBounds(new java.awt.Rectangle(100, 100, 100, 100));
        setResizable(false);

        panel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 0)));
        panel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Recursos/fondo1.jpg"))); // NOI18N
        panel1.setLayout(null);

        labelMetric1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelMetric1.setText("INICIE SESION");
        labelMetric1.setFont(new java.awt.Font("AR DELANEY", 1, 24)); // NOI18N
        panel1.add(labelMetric1);
        labelMetric1.setBounds(80, 60, 200, 30);

        labelMetric2.setText("Tipo de usuario:");
        panel1.add(labelMetric2);
        labelMetric2.setBounds(20, 120, 120, 17);

        labelMetric3.setText("Contraseña :");
        panel1.add(labelMetric3);
        labelMetric3.setBounds(40, 200, 100, 17);

        Txtusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtusuarioActionPerformed(evt);
            }
        });
        Txtusuario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtusuarioKeyPressed(evt);
            }
        });
        panel1.add(Txtusuario);
        Txtusuario.setBounds(160, 120, 180, 21);

        Txtcontraseña.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                TxtcontraseñaKeyPressed(evt);
            }
        });
        panel1.add(Txtcontraseña);
        Txtcontraseña.setBounds(160, 200, 180, 21);

        clockDigital1.setForeground(new java.awt.Color(255, 255, 255));
        panel1.add(clockDigital1);
        clockDigital1.setBounds(0, 10, 150, 49);

        BotIniciaSecion.setBackground(new java.awt.Color(0, 255, 255));
        BotIniciaSecion.setText("Iniciar Sesion");
        BotIniciaSecion.setColorDeSombra(new java.awt.Color(0, 0, 255));
        BotIniciaSecion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotIniciaSecionActionPerformed(evt);
            }
        });
        panel1.add(BotIniciaSecion);
        BotIniciaSecion.setBounds(150, 340, 127, 25);
        panel1.add(jProgressBar1);
        jProgressBar1.setBounds(90, 280, 280, 14);

        labelMetric4.setText("Usuario :");
        panel1.add(labelMetric4);
        labelMetric4.setBounds(70, 160, 70, 17);

        Txtusuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Txtusuario1ActionPerformed(evt);
            }
        });
        Txtusuario1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                Txtusuario1KeyPressed(evt);
            }
        });
        panel1.add(Txtusuario1);
        Txtusuario1.setBounds(160, 160, 180, 21);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 483, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, 391, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TxtusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtusuarioActionPerformed
        
    }//GEN-LAST:event_TxtusuarioActionPerformed

    private void BotIniciaSecionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotIniciaSecionActionPerformed
        Ingresar_Usuario();
        FormPrincipal_Prueba p= new FormPrincipal_Prueba();
        p.setLocationRelativeTo(p);
        p.show(true);
    }//GEN-LAST:event_BotIniciaSecionActionPerformed

    private void TxtusuarioKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtusuarioKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.Txtcontraseña.requestFocus();
        }
    }//GEN-LAST:event_TxtusuarioKeyPressed

    private void TxtcontraseñaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtcontraseñaKeyPressed
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            this.BotIniciaSecion.requestFocus();
        }
    }//GEN-LAST:event_TxtcontraseñaKeyPressed

    private void Txtusuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Txtusuario1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtusuario1ActionPerformed

    private void Txtusuario1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_Txtusuario1KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_Txtusuario1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(from_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(from_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(from_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(from_usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new from_usuario().setVisible(true);
                from_usuario fu = new from_usuario();
                fu.setLocationRelativeTo(fu);
                fu.show(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private org.edisoncor.gui.button.ButtonTextDown BotIniciaSecion;
    private org.edisoncor.gui.passwordField.PasswordField Txtcontraseña;
    private org.edisoncor.gui.textField.TextField Txtusuario;
    private org.edisoncor.gui.textField.TextField Txtusuario1;
    private org.edisoncor.gui.varios.ClockDigital clockDigital1;
    private javax.swing.JProgressBar jProgressBar1;
    private org.edisoncor.gui.label.LabelMetric labelMetric1;
    private org.edisoncor.gui.label.LabelMetric labelMetric2;
    private org.edisoncor.gui.label.LabelMetric labelMetric3;
    private org.edisoncor.gui.label.LabelMetric labelMetric4;
    private org.edisoncor.gui.panel.Panel panel1;
    // End of variables declaration//GEN-END:variables
}
